# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGbDVpxzJ_Sujqk-Kck1XRrCJzbrxir5
"""

import numpy as np


a = 1
b = 2
n = 11

h = (b - a) / (n - 1)

x = np.linspace(a, b, n)

f = np.exp(x) * np.sin(4 * x)

I_trap = (h / 2) * (f[0] + 2 * np.sum(f[1:n-1]) + f[-1])

print("Approximate integral using trapezoidal rule =", I_trap)